# Generated by Django 3.2.12 on 2022-07-07 01:19

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('branchSource', models.CharField(blank=True, max_length=50)),
                ('branchDestiny', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_merge', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
